project:
  type: website

website:
  title: "GIS_Project"
  navbar:
    left: 
      - href: intro.qmd
        text: Introduction
      - href: methodology.qmd
        text: Methodology
      - href: analysis.qmd
        text: Analysis
      - href: finding.qmd
        text: Results & Discussion
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
